### ISSUE TITLE
所有设备均无法绑定，请自己寻找可用的qrcode，将连接加入列表qr中进行尝试。

### ISSUE THREAD

**Issue by wy1ng** [ne-21/lx-step#1]
请问如何获取自己的qrcode？如果大家都能用自己的话就没啥问题了吧

**Comment by ne-21** [comment]
> 请问如何获取自己的qrcode？如果大家都能用自己的话就没啥问题了吧

应该是的，qrcode获取直接在手机上抓绑定设备的包就可以

**Comment by wy1ng** [comment]
请问有没得抓包教程。。。。

**Comment by ne-21** [comment]
> 请问有没得抓包教程。。。。

手机下载抓包精灵，使用教程百度，然后去乐心绑定设备，再去抓包精灵里找绑定的包，里面会有qrcode参数
